pickledb:
  base_dir: /tmp
  filename: results.db
accounts:
  - id: 112398043980
    alias: langton
    profile: chris
    assumeRole: read-only
    regions:
      - ap-sounteast-2
      - us-east-1
outputs:
  compliant:
    base_dir: /tmp
    filename: aws-scan-compliant.log
  non_compliant:
    base_dir: /tmp
    filename: aws-scan-non-compliant.log
compliance:
  "iam-key-max-age-days": 30